version: '3.8'

services:
  # Serviço da nossa API FastAPI
  api:
    build: .
    container_name: urbanxp_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app # Monta o código local para live reload durante o desenvolvimento
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: urbanxp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # Serviço do Redis (para cache e Celery)
  redis:
    image: redis:6-alpine
    container_name: urbanxp_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: